### ISSUE TITLE
Cannot install to theos

### ISSUE THREAD

**Issue by atrt7** [opa334/AltList#20]
This is the output I get when I run ./install_to_theos.sh

`==> Cleaning…
> Making clean in AltListTestBundle…
==> Cleaning…
> Making all for framework AltList…
==> Copying resource directories into the framework wrapper…
==> Copying public headers into the framework wrapper…
==> Preprocessing AltList.x…
==> Preprocessing AltList.x…
==> Compiling ATLApplicationListControllerBase.m (armv7)…
ATLApplicationListControllerBase.m:14:6: error: comparison of function 'dispatch_queue_attr_make_with_qos_class' not equal to a null pointer is always true [-Werror,-Wtautological-pointer-compare]
        if (dispatch_queue_attr_make_with_qos_class != NULL)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    ~~~~
ATLApplicationListControllerBase.m:14:6: note: prefix with the address-of operator to silence this warning
        if (dispatch_queue_attr_make_with_qos_class != NULL)
            ^
            &
1 error generated.
make[3]: *** [/home/atrt7/theos/makefiles/instance/rules.mk:193: /home/atrt7/AltList/.theos/obj/armv7/ATLApplicationListControllerBase.m.9349dfb3.o] Error 1
make[3]: *** Waiting for unfinished jobs....
==> Compiling ATLApplicationListControllerBase.m (arm64)…
ATLApplicationListControllerBase.m:14:6: error: comparison of function 'dispatch_queue_attr_make_with_qos_class' not equal to a null pointer is always true [-Werror,-Wtautological-pointer-compare]
        if (dispatch_queue_attr_make_with_qos_class != NULL)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    ~~~~
ATLApplicationListControllerBase.m:14:6: note: prefix with the address-of operator to silence this warning
        if (dispatch_queue_attr_make_with_qos_class != NULL)
            ^
            &
1 error generated.
make[3]: *** [/home/atrt7/theos/makefiles/instance/rules.mk:193: /home/atrt7/AltList/.theos/obj/arm64/ATLApplicationListControllerBase.m.2699f159.o] Error 1
make[3]: *** Waiting for unfinished jobs....
==> Compiling ATLApplicationListMultiSelectionController.m (armv7)…
rm /home/atrt7/AltList/.theos/obj/armv7/AltList.x.m
make[2]: *** [/home/atrt7/theos/makefiles/instance/framework.mk:36: /home/atrt7/AltList/.theos/obj/armv7/AltList.framework/AltList] Error 2
make[2]: *** Waiting for unfinished jobs....
==> Compiling ATLApplicationListMultiSelectionController.m (arm64)…
==> Compiling ATLApplicationListSelectionController.m (arm64)…
rm /home/atrt7/AltList/.theos/obj/arm64/AltList.x.m
make[2]: *** [/home/atrt7/theos/makefiles/instance/framework.mk:36: /home/atrt7/AltList/.theos/obj/arm64/AltList.framework/AltList] Error 2
make[1]: *** [/home/atrt7/theos/makefiles/instance/framework.mk:27: internal-framework-all_] Error 2
make: *** [/home/atrt7/theos/makefiles/master/rules.mk:117: AltList.all.framework.variables] Error 2`

**Comment by opa334** [comment]
Did you by any chance bump the deployment target? (the last value here https://github.com/opa334/AltList/blob/main/Makefile#L3). This error only seems to come up for me when I make it higher then 7.0.

**Comment by atrt7** [comment]
I did not, the only thing I changed was adding an export SYSROOT to the path to the sdk

**Comment by opa334** [comment]
Try again now, should be fixed.

**Comment by atrt7** [comment]
There are apparently other errors

`==> Cleaning…
> Making clean in AltListTestPreferences…
==> Cleaning…
> Making clean in AltListTestBundlelessPreferences…
==> Cleaning…
> Making all for framework AltList…
==> Copying resource directories into the framework wrapper…
==> Copying public headers into the framework wrapper…
==> Preprocessing AltList.x…
==> Preprocessing AltList.x…
==> Compiling ATLApplicationListMultiSelectionController.m (armv7)…
==> Compiling ATLApplicationListSelectionController.m (armv7)…
==> Compiling ATLApplicationListSubcontrollerController.m (armv7)…
==> Compiling ATLApplicationSection.m (armv7)…
In file included from ATLApplicationSection.m:1:
./ATLApplicationSection.h:2:52: error: function definition declared 'typedef'
typedef NS_ENUM(NSInteger, ApplicationSectionType) {
                                                   ^
./ATLApplicationSection.h:2:9: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
typedef NS_ENUM(NSInteger, ApplicationSectionType) {
~~~~~~~ ^
./ATLApplicationSection.h:3:2: error: use of undeclared identifier 'SECTION_TYPE_ALL'
        SECTION_TYPE_ALL,
        ^
./ATLApplicationSection.h:4:5: error: use of undeclared identifier 'SECTION_TYPE_SYSTEM'
    SECTION_TYPE_SYSTEM,
    ^
./ATLApplicationSection.h:5:2: error: use of undeclared identifier 'SECTION_TYPE_USER'
        SECTION_TYPE_USER,
        ^
./ATLApplicationSection.h:6:2: error: use of undeclared identifier 'SECTION_TYPE_HIDDEN'
        SECTION_TYPE_HIDDEN,
        ^
./ATLApplicationSection.h:7:2: error: use of undeclared identifier 'SECTION_TYPE_VISIBLE'
        SECTION_TYPE_VISIBLE,
        ^
./ATLApplicationSection.h:8:2: error: use of undeclared identifier 'SECTION_TYPE_CUSTOM'
        SECTION_TYPE_CUSTOM
        ^
./ATLApplicationSection.h:18:36: error: cannot find interface declaration for 'NSObject', superclass of 'ATLApplicationSection'
@interface ATLApplicationSection : NSObject
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ^
./ATLApplicationSection.h:19:23: error: unknown type name 'ApplicationSectionType'; did you mean 'ATLApplicationSection'?
@property (nonatomic) ApplicationSectionType sectionType;
                      ^~~~~~~~~~~~~~~~~~~~~~
                      ATLApplicationSection                                                                                                                            
./ATLApplicationSection.h:18:12: note: 'ATLApplicationSection' declared here
@interface ATLApplicationSection : NSObject
           ^
./ATLApplicationSection.h:19:46: error: interface type cannot be statically allocated
@property (nonatomic) ApplicationSectionType sectionType;
                                             ^
                                            *                                                                                                                          
./ATLApplicationSection.h:20:23: error: unknown type name 'NSPredicate'
@property (nonatomic) NSPredicate* customPredicate;
                      ^
./ATLApplicationSection.h:21:23: error: unknown type name 'NSString'
@property (nonatomic) NSString* sectionName;
                      ^
./ATLApplicationSection.h:23:23: error: unknown type name 'NSArray'
@property (nonatomic) NSArray* applicationsInSection;
                      ^
./ATLApplicationSection.h:25:4: error: expected a type
+ (ApplicationSectionType)sectionTypeFromString:(NSString*)typeString;
   ^
./ATLApplicationSection.h:25:50: error: expected a type
+ (ApplicationSectionType)sectionTypeFromString:(NSString*)typeString;
                                                 ^
./ATLApplicationSection.h:26:4: error: expected a type
+ (NSString*)stringFromSectionType:(ApplicationSectionType)sectionType;
   ^
./ATLApplicationSection.h:26:37: error: expected a type
+ (NSString*)stringFromSectionType:(ApplicationSectionType)sectionType;
                                    ^
./ATLApplicationSection.h:28:70: error: expected a type
+ (__kindof ATLApplicationSection*)applicationSectionWithDictionary:(NSDictionary*)sectionDictionary;
                                                                     ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[3]: *** [/home/atrt7/theos/makefiles/instance/rules.mk:193: /home/atrt7/AltList/.theos/obj/armv7/ATLApplicationSection.m.b8dfa390.o] Error 1
make[3]: *** Waiting for unfinished jobs....
==> Compiling ATLApplicationListSubcontroller.m (armv7)…
==> Compiling ATLApplicationListControllerBase.m (armv7)…
rm /home/atrt7/AltList/.theos/obj/armv7/AltList.x.m
make[2]: *** [/home/atrt7/theos/makefiles/instance/framework.mk:36: /home/atrt7/AltList/.theos/obj/armv7/AltList.framework/AltList] Error 2
make[2]: *** Waiting for unfinished jobs....
==> Compiling ATLApplicationListMultiSelectionController.m (arm64)…
==> Compiling ATLApplicationListControllerBase.m (arm64)…
==> Compiling ATLApplicationListSelectionController.m (arm64)…
==> Compiling ATLApplicationSection.m (arm64)…
In file included from ATLApplicationSection.m:1:
./ATLApplicationSection.h:2:52: error: function definition declared 'typedef'
typedef NS_ENUM(NSInteger, ApplicationSectionType) {
                                                   ^
./ATLApplicationSection.h:2:9: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
typedef NS_ENUM(NSInteger, ApplicationSectionType) {
~~~~~~~ ^
./ATLApplicationSection.h:3:2: error: use of undeclared identifier 'SECTION_TYPE_ALL'
        SECTION_TYPE_ALL,
        ^
./ATLApplicationSection.h:4:5: error: use of undeclared identifier 'SECTION_TYPE_SYSTEM'
    SECTION_TYPE_SYSTEM,
    ^
./ATLApplicationSection.h:5:2: error: use of undeclared identifier 'SECTION_TYPE_USER'
        SECTION_TYPE_USER,
        ^
./ATLApplicationSection.h:6:2: error: use of undeclared identifier 'SECTION_TYPE_HIDDEN'
        SECTION_TYPE_HIDDEN,
        ^
./ATLApplicationSection.h:7:2: error: use of undeclared identifier 'SECTION_TYPE_VISIBLE'
        SECTION_TYPE_VISIBLE,
        ^
./ATLApplicationSection.h:8:2: error: use of undeclared identifier 'SECTION_TYPE_CUSTOM'
        SECTION_TYPE_CUSTOM
        ^
./ATLApplicationSection.h:18:36: error: cannot find interface declaration for 'NSObject', superclass of 'ATLApplicationSection'
@interface ATLApplicationSection : NSObject
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   ^
./ATLApplicationSection.h:19:23: error: unknown type name 'ApplicationSectionType'; did you mean 'ATLApplicationSection'?
@property (nonatomic) ApplicationSectionType sectionType;
                      ^~~~~~~~~~~~~~~~~~~~~~
                      ATLApplicationSection                                                                                                                            
./ATLApplicationSection.h:18:12: note: 'ATLApplicationSection' declared here
@interface ATLApplicationSection : NSObject
           ^
./ATLApplicationSection.h:19:46: error: interface type cannot be statically allocated
@property (nonatomic) ApplicationSectionType sectionType;
                                             ^
                                            *                                                                                                                          
./ATLApplicationSection.h:20:23: error: unknown type name 'NSPredicate'
@property (nonatomic) NSPredicate* customPredicate;
                      ^
./ATLApplicationSection.h:21:23: error: unknown type name 'NSString'
@property (nonatomic) NSString* sectionName;
                      ^
./ATLApplicationSection.h:23:23: error: unknown type name 'NSArray'
@property (nonatomic) NSArray* applicationsInSection;
                      ^
./ATLApplicationSection.h:25:4: error: expected a type
+ (ApplicationSectionType)sectionTypeFromString:(NSString*)typeString;
   ^
./ATLApplicationSection.h:25:50: error: expected a type
+ (ApplicationSectionType)sectionTypeFromString:(NSString*)typeString;
                                                 ^
./ATLApplicationSection.h:26:4: error: expected a type
+ (NSString*)stringFromSectionType:(ApplicationSectionType)sectionType;
   ^
./ATLApplicationSection.h:26:37: error: expected a type
+ (NSString*)stringFromSectionType:(ApplicationSectionType)sectionType;
                                    ^
./ATLApplicationSection.h:28:70: error: expected a type
+ (__kindof ATLApplicationSection*)applicationSectionWithDictionary:(NSDictionary*)sectionDictionary;
                                                                     ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[3]: *** [/home/atrt7/theos/makefiles/instance/rules.mk:193: /home/atrt7/AltList/.theos/obj/arm64/ATLApplicationSection.m.e800d1dd.o] Error 1
make[3]: *** Waiting for unfinished jobs....
==> Compiling ATLApplicationListSubcontrollerController.m (arm64)…
==> Compiling ATLApplicationListSubcontroller.m (arm64)…
==> Compiling ATLApplicationSelectionCell.m (arm64)…
rm /home/atrt7/AltList/.theos/obj/arm64/AltList.x.m
make[2]: *** [/home/atrt7/theos/makefiles/instance/framework.mk:36: /home/atrt7/AltList/.theos/obj/arm64/AltList.framework/AltList] Error 2
make[1]: *** [/home/atrt7/theos/makefiles/instance/framework.mk:27: internal-framework-all_] Error 2
make: *** [/home/atrt7/theos/makefiles/master/rules.mk:117: AltList.all.framework.variables] Error 2`

**Comment by opa334** [comment]
it's definitely an issue with the SYSROOT you tried to set, just make sure that iPhoneOS13.0.sdk from https://github.com/xybp888/iOS-SDKs is in $THEOS/sdks and then it should compile without any modifications.

**Comment by atrt7** [comment]
I appear to get the same error with those sdks installed, although no modifications were required. I am compiling on linux btw it might be the toolchain I am using

**Comment by opa334** [comment]
just extract this and put AltList.framework into $THEOS/lib

https://www.mediafire.com/file/u5xna6dculixmyr/AltList.framework.zip/file

**Comment by opa334** [comment]
figured out the exact problem - the version of theos I was using is outdated, after updating it get the same issues

**Comment by opa334** [comment]
actually nvm, it's this problem and a bug in theos https://github.com/theos/theos/issues/552
