### ISSUE TITLE
AltList 1.0.5-2 crash

### ISSUE THREAD

**Issue by sadalhayat** [opa334/AltList#25]
iOS Settings crashes when I tried to open any preference which have com.opa334.altlist dependencies, such as: Crane, Bakgrunnur, bfdecrypt.

Crash log:
https://pastebin.com/aaRegR5L

💥 AltList versions that crash: 
1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5-2
✅ Worked fine with AltList 1.0-1

Device: iPhone 12 Pro Max
iOS: 14.3
Jailbreak: Taurine 1.0.4

**Comment by opa334** [comment]
There is absolutely no mention of AltList in that crashlog, weird...

Can you install Cr4shed and get me a log from there? You may have to retrigger the crash for the log to appear.

**Comment by sadalhayat** [comment]
Crash log from Cr4shed

https://pastebin.com/F7SXEb1q

**Comment by opa334** [comment]
sigh... you have an application installed that has a malformed Info.plist, I'm not sure how this is a thing but I will add some type checks so this doesn't crash

**Comment by opa334** [comment]
please test if this fixes it, if it does then I will push it tomorrow https://www.mediafire.com/file/4mhcg5xhlj79pfx/com.opa334.altlist_1.0.5-2-3%252Bdebug_iphoneos-arm.deb/file

**Comment by sadalhayat** [comment]
> please test if this fixes it, if it does then I will push it tomorrow https://www.mediafire.com/file/4mhcg5xhlj79pfx/com.opa334.altlist_1.0.5-2-3%252Bdebug_iphoneos-arm.deb/file

Perfect! Works fine.
Thanks you very much.
![screenshot](https://telegra.ph/file/60854605f6776c9e7fdc1.jpg)
