### ISSUE TITLE
not found Altlist.h!

### ISSUE THREAD

**Issue by ghost** [opa334/AltList#34]
![image](https://github.com/opa334/AltList/assets/58970079/741b2e7e-140b-4324-832e-5abeba066611)

After I ran the installation script you provided, it also prompted that it was successful. However, when I tried to introduce it, it prompted that it could not be found!
I have tried many methods, asked most people, and looked at most examples, but none of them worked!

Help me！！！！/(ㄒoㄒ)/~~

**Comment by opa334** [comment]
Ensure `$(THEOS)/include` is in your header search paths.
